% This script calls the 'IMUImport' function which imports data from text
% files generated by the Xsens Awinda motion capture sensors using the MTw
% StationManager. This function puts the data into a cell array called
% 'data' and saves it under the name 'Trial Data Imported.' Each row of 
% 'data' corresponds to a given file. The first column of 'data'
% corresponds to the file name, the second column contains a matrix of the
% values of the file's data table, and the third column contains matrices
% that specifically contain the file's quaternion outputs.
DIR = pwd;
cd(strcat(DIR,'/Subject Information'))
disp('Load subject information ("P_xxx_Info.mat")')
[SOfile SOdir] = uigetfile;
load(strcat(SOdir,SOfile))
clc

cd(strcat(DIR,'/Subject Data Text Files'))
disp('Select trial folder')
TDdir = uigetdir;
cd(DIR)
data = IMUImport(TDdir,QuatColumnOne,RowStart,TaskList,num,NumberSensors);
clc

disp('Enter a name to save the trial data under')
disp('Make sure to enter a valid name for a .mat file')
disp('Also remember to type apostrophes when entering a string')
disp(strcat('(ie',32,39,'FileName',39,32,',not FileName)'))    
saveas = input('Save file as? (type a file name)');
save(strcat(DIR,'\Imported Subject Data\',saveas),'data')
clc